import { NextRequest, NextResponse } from 'next/server';
import { getUser } from '@/lib/supabase-server';

export const runtime = 'nodejs';

/**
 * POST /api/transmittals/generate
 * Body: { to, from, projectName, re?, date?, transmittalNo?, items: [{ description, copies?, action? }] }
 *
 * Generates a professional transmittal cover sheet (PDF) — who/what/why plus a
 * table of the documents being transmitted with action codes. Procore parity.
 */
export async function POST(req: NextRequest) {
  const user = await getUser(req);
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  let b: { to?: string; from?: string; projectName?: string; re?: string; date?: string; transmittalNo?: string;
    items?: { description?: string; copies?: string | number; action?: string }[]; fileName?: string };
  try { b = await req.json(); } catch { return NextResponse.json({ error: 'Invalid body' }, { status: 400 }); }
  const items = b.items || [];

  try {
    const { PDFDocument, StandardFonts, rgb } = await import('pdf-lib');
    const pdf = await PDFDocument.create();
    const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
    const reg = await pdf.embedFont(StandardFonts.Helvetica);
    const page = pdf.addPage([612, 792]);
    const GOLD = rgb(0.831, 0.627, 0.09); const DARK = rgb(0.05, 0.07, 0.09);
    const WHITE = rgb(1, 1, 1); const GRAY = rgb(0.42, 0.36, 0.26); const LINE = rgb(0.85, 0.85, 0.85);
    const M = 48;

    page.drawRectangle({ x: 0, y: 792 - 92, width: 612, height: 92, color: DARK });
    page.drawText('SAGUARO', { x: M, y: 792 - 40, size: 12, font: bold, color: GOLD });
    page.drawText('LETTER OF TRANSMITTAL', { x: M, y: 792 - 66, size: 20, font: bold, color: WHITE });
    page.drawText(`No. ${b.transmittalNo || new Date().getTime().toString().slice(-6)}`, { x: 612 - M - 110, y: 792 - 40, size: 11, font: bold, color: GOLD });

    const date = b.date || new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric', timeZone: 'America/Phoenix' });
    const fields: [string, string][] = [
      ['Project', b.projectName || '—'], ['Date', date], ['To', b.to || '—'], ['From', b.from || '—'], ['Re', b.re || '—'],
    ];
    let y = 792 - 124;
    for (const [label, val] of fields) {
      page.drawText(label.toUpperCase(), { x: M, y, size: 8, font: bold, color: GRAY });
      page.drawText(String(val).slice(0, 80), { x: M + 70, y, size: 12, font: reg, color: DARK });
      y -= 26;
    }

    y -= 8;
    // Items table header
    page.drawRectangle({ x: M, y: y - 4, width: 612 - M * 2, height: 22, color: DARK });
    page.drawText('#', { x: M + 8, y: y + 2, size: 9, font: bold, color: WHITE });
    page.drawText('DESCRIPTION', { x: M + 40, y: y + 2, size: 9, font: bold, color: WHITE });
    page.drawText('COPIES', { x: 612 - M - 150, y: y + 2, size: 9, font: bold, color: WHITE });
    page.drawText('ACTION', { x: 612 - M - 90, y: y + 2, size: 9, font: bold, color: WHITE });
    y -= 26;
    items.slice(0, 22).forEach((it, i) => {
      page.drawText(String(i + 1), { x: M + 8, y, size: 10, font: reg, color: DARK });
      page.drawText(String(it.description || '').slice(0, 56), { x: M + 40, y, size: 10, font: reg, color: DARK });
      page.drawText(String(it.copies ?? '1'), { x: 612 - M - 150, y, size: 10, font: reg, color: DARK });
      page.drawText(String(it.action || 'For Review').slice(0, 16), { x: 612 - M - 90, y, size: 9, font: reg, color: GRAY });
      page.drawLine({ start: { x: M, y: y - 6 }, end: { x: 612 - M, y: y - 6 }, thickness: 0.5, color: LINE });
      y -= 22;
    });

    page.drawText('Transmitted for the action noted above.', { x: M, y: 70, size: 9, font: reg, color: GRAY });
    page.drawText(`Generated by Saguaro • ${date}`, { x: M, y: 54, size: 8, font: reg, color: GRAY });

    const bytes = await pdf.save();
    const fileName = (b.fileName || 'transmittal').replace(/[^a-z0-9_\-]+/gi, '-');
    return new NextResponse(Buffer.from(bytes), {
      headers: { 'Content-Type': 'application/pdf', 'Content-Disposition': `attachment; filename="${fileName}.pdf"` },
    });
  } catch (err) {
    console.error('[transmittals/generate]', err);
    return NextResponse.json({ error: 'Transmittal generation failed' }, { status: 500 });
  }
}
