export interface Competitor {
  slug: string;           // URL slug, e.g. 'buildertrend'
  name: string;           // Display name, e.g. 'Buildertrend'
  tagline: string;        // Their positioning
  targetMarket: string;   // Who they serve
  startingPrice: string;  // Their pricing
  annualRequired: boolean;
  setupTime: string;
  perSeat: boolean;
  hasAITakeoff: boolean;
  hasLienWaivers: boolean;
  hasCertifiedPayroll: boolean;
  hasFieldApp: boolean;
  appStoreRequired: boolean;
  hasOfflineMode: boolean;
  hasBidIntelligence: boolean;
  hasClientPortal: boolean;
  hasSubPortal: boolean;
  weaknesses: string[];   // 3-4 weaknesses
  bestFor: string;        // Who the competitor is best for (honest)
  saguaroAdvantage: string; // One-line why Saguaro wins
  heroHeadline: string;   // Page hero headline
  heroSubheadline: string;
  metaTitle: string;
  metaDescription: string;
  searchKeywords: string[];
}

export const COMPETITORS: Record<string, Competitor> = {
  buildertrend: {
    slug: 'buildertrend',
    name: 'Buildertrend',
    tagline: 'Project management for home builders and remodelers',
    targetMarket: 'Residential builders and remodelers',
    startingPrice: '$499/mo',
    annualRequired: false,
    setupTime: '2–4 weeks',
    perSeat: false,
    hasAITakeoff: false,
    hasLienWaivers: false,
    hasCertifiedPayroll: false,
    hasFieldApp: true,
    appStoreRequired: true,
    hasOfflineMode: false,
    hasBidIntelligence: false,
    hasClientPortal: true,
    hasSubPortal: true,
    weaknesses: [
      'No AI blueprint takeoff — estimating still manual',
      'No lien waivers — requires third-party integration',
      'No certified payroll WH-347 for prevailing wage jobs',
      'No offline field app — requires cell signal on site',
      'Built for residential only — limited for commercial GCs',
    ],
    bestFor: 'Small residential builders and remodelers who need basic scheduling and client communication',
    saguaroAdvantage: 'AI takeoff + lien waivers + certified payroll + offline field app — all missing from Buildertrend',
    heroHeadline: 'Everything Buildertrend Does,\nPlus the AI Buildertrend Doesn\'t Have',
    heroSubheadline: 'Saguaro gives you AI blueprint takeoff, lien waivers in all 50 states, certified payroll, and a field app that works offline — none of which Buildertrend offers.',
    metaTitle: 'Saguaro vs Buildertrend — Full Comparison 2025',
    metaDescription: 'Buildertrend vs Saguaro: See how AI takeoff, lien waivers, certified payroll, and offline mode stack up. Starting at $199/mo vs Buildertrend\'s $499/mo.',
    searchKeywords: ['buildertrend alternative', 'buildertrend vs saguaro', 'buildertrend competitor', 'buildertrend replacement'],
  },
  coconstruct: {
    slug: 'coconstruct',
    name: 'CoConstruct',
    tagline: 'Custom home builder and remodeler software',
    targetMarket: 'Custom home builders',
    startingPrice: '$499/mo',
    annualRequired: false,
    setupTime: '2–3 weeks',
    perSeat: false,
    hasAITakeoff: false,
    hasLienWaivers: false,
    hasCertifiedPayroll: false,
    hasFieldApp: true,
    appStoreRequired: true,
    hasOfflineMode: false,
    hasBidIntelligence: false,
    hasClientPortal: true,
    hasSubPortal: false,
    weaknesses: [
      'No AI blueprint takeoff or estimating automation',
      'No lien waiver management for any state',
      'No certified payroll — manual WH-347 forms',
      'Merged into Buildertrend — product direction uncertain',
      'No commercial construction support',
    ],
    bestFor: 'Custom home builders who need client communication and selections management',
    saguaroAdvantage: 'AI takeoff + lien waivers + certified payroll — all built in, no integrations needed',
    heroHeadline: 'The CoConstruct Alternative\nBuilt for the AI Era',
    heroSubheadline: 'CoConstruct (now Buildertrend) still has no AI takeoff, no lien waivers, and no certified payroll. Saguaro has all three — plus a field app that works offline.',
    metaTitle: 'Saguaro vs CoConstruct — Full Comparison 2025',
    metaDescription: 'CoConstruct vs Saguaro: AI takeoff, lien waivers, certified payroll — all missing from CoConstruct. See why GCs are switching.',
    searchKeywords: ['coconstruct alternative', 'coconstruct vs saguaro', 'coconstruct replacement', 'coconstruct competitor'],
  },
  fieldwire: {
    slug: 'fieldwire',
    name: 'Fieldwire',
    tagline: 'Jobsite management and plan viewing',
    targetMarket: 'Field teams and superintendents',
    startingPrice: '$54/user/mo',
    annualRequired: true,
    setupTime: '1–2 weeks',
    perSeat: true,
    hasAITakeoff: false,
    hasLienWaivers: false,
    hasCertifiedPayroll: false,
    hasFieldApp: true,
    appStoreRequired: true,
    hasOfflineMode: true,
    hasBidIntelligence: false,
    hasClientPortal: false,
    hasSubPortal: false,
    weaknesses: [
      'Per-seat pricing — costs grow with every new user',
      'No AI takeoff — field management only, no estimating',
      'No lien waivers, pay apps, or financial features',
      'No certified payroll or compliance tools',
      'Field management only — not a full CRM or PM platform',
    ],
    bestFor: 'Large teams who need plan viewing and field task management only',
    saguaroAdvantage: 'Full platform (estimating → billing → field) vs Fieldwire\'s field-only scope, at flat pricing',
    heroHeadline: 'Beyond Fieldwire:\nThe Complete Platform Fieldwire Can\'t Be',
    heroSubheadline: 'Fieldwire is great for viewing plans. Saguaro does that plus AI takeoff, lien waivers, pay apps, bid management, and certified payroll — at one flat price for your whole team.',
    metaTitle: 'Saguaro vs Fieldwire — Full Comparison 2025',
    metaDescription: 'Fieldwire vs Saguaro: Fieldwire charges per seat and covers field management only. Saguaro is a full platform at flat pricing — AI takeoff to certified payroll.',
    searchKeywords: ['fieldwire alternative', 'fieldwire vs saguaro', 'fieldwire replacement', 'fieldwire competitor'],
  },
  'autodesk-build': {
    slug: 'autodesk-build',
    name: 'Autodesk Build',
    tagline: 'Construction document and project management',
    targetMarket: 'Large commercial GCs and ENR contractors',
    startingPrice: '$500/user/yr',
    annualRequired: true,
    setupTime: '1–3 months',
    perSeat: true,
    hasAITakeoff: false,
    hasLienWaivers: false,
    hasCertifiedPayroll: false,
    hasFieldApp: true,
    appStoreRequired: true,
    hasOfflineMode: true,
    hasBidIntelligence: false,
    hasClientPortal: true,
    hasSubPortal: true,
    weaknesses: [
      'Per-seat annual pricing — extremely expensive at scale',
      'No AI blueprint takeoff native to the platform',
      'No lien waiver management included',
      'No certified payroll WH-347',
      'Enterprise complexity — overkill for most GCs under $50M',
    ],
    bestFor: 'ENR Top 400 contractors with dedicated BIM/VDC teams',
    saguaroAdvantage: 'AI takeoff, flat pricing, lien waivers, certified payroll — all at a fraction of Autodesk\'s cost',
    heroHeadline: 'Autodesk Build Pricing Is\nEnterprise. Your Work Isn\'t.',
    heroSubheadline: 'Autodesk Build costs $500+/user/year and still has no AI takeoff. Saguaro gives mid-market GCs everything they need at $399/mo flat — the whole team, one price.',
    metaTitle: 'Saguaro vs Autodesk Build — Full Comparison 2025',
    metaDescription: 'Autodesk Build vs Saguaro: Enterprise pricing vs flat rate. AI takeoff, lien waivers, certified payroll included in Saguaro. No per-seat fees.',
    searchKeywords: ['autodesk build alternative', 'plangrid alternative', 'autodesk construction cloud alternative', 'autodesk build vs saguaro'],
  },
  'contractor-foreman': {
    slug: 'contractor-foreman',
    name: 'Contractor Foreman',
    tagline: 'Affordable construction management software',
    targetMarket: 'Small GCs and self-perform contractors',
    startingPrice: '$49/mo',
    annualRequired: false,
    setupTime: '1 week',
    perSeat: false,
    hasAITakeoff: false,
    hasLienWaivers: false,
    hasCertifiedPayroll: false,
    hasFieldApp: true,
    appStoreRequired: true,
    hasOfflineMode: false,
    hasBidIntelligence: false,
    hasClientPortal: true,
    hasSubPortal: false,
    weaknesses: [
      'No AI features — fully manual estimating',
      'No lien waiver management',
      'No certified payroll for prevailing wage jobs',
      'No offline field app',
      'Limited scalability for growing teams',
    ],
    bestFor: 'Solo contractors and very small GCs needing basic PM at low cost',
    saguaroAdvantage: 'AI takeoff saves 4+ hours per bid — more than pays for the cost difference vs Contractor Foreman',
    heroHeadline: 'Outgrown Contractor Foreman?\nHere\'s What\'s Next.',
    heroSubheadline: 'Contractor Foreman is a great starter tool. But when you\'re ready for AI takeoff, lien waivers, and certified payroll, Saguaro is the natural next step.',
    metaTitle: 'Saguaro vs Contractor Foreman — Full Comparison 2025',
    metaDescription: 'Contractor Foreman vs Saguaro: See which is right for your GC business. AI takeoff, lien waivers, certified payroll — all in Saguaro but not Contractor Foreman.',
    searchKeywords: ['contractor foreman alternative', 'contractor foreman vs saguaro', 'contractor foreman replacement'],
  },
  jobber: {
    slug: 'jobber',
    name: 'Jobber',
    tagline: 'Field service management for home service businesses',
    targetMarket: 'Home service and field service businesses',
    startingPrice: '$49/mo',
    annualRequired: false,
    setupTime: '< 1 week',
    perSeat: false,
    hasAITakeoff: false,
    hasLienWaivers: false,
    hasCertifiedPayroll: false,
    hasFieldApp: true,
    appStoreRequired: true,
    hasOfflineMode: false,
    hasBidIntelligence: false,
    hasClientPortal: true,
    hasSubPortal: false,
    weaknesses: [
      'Built for service businesses — not construction GCs',
      'No blueprint takeoff or estimating for construction',
      'No lien waivers, pay apps, or AIA documents',
      'No certified payroll or prevailing wage tools',
      'No subcontractor management or compliance tracking',
    ],
    bestFor: 'HVAC, plumbing, cleaning, and landscaping service companies — not construction GCs',
    saguaroAdvantage: 'Built specifically for construction: AIA documents, lien waivers, takeoff, certified payroll — Jobber has none of these',
    heroHeadline: 'Jobber Is for Service Companies.\nSaguaro Is Built for Builders.',
    heroSubheadline: 'If you\'re a general contractor doing construction, Jobber doesn\'t have what you need. Saguaro has AI takeoff, AIA pay apps, lien waivers in 50 states, and certified payroll.',
    metaTitle: 'Saguaro vs Jobber for Construction — Full Comparison 2025',
    metaDescription: 'Jobber vs Saguaro: Jobber is for field service businesses, not construction GCs. Saguaro has AI takeoff, AIA documents, lien waivers, and certified payroll.',
    searchKeywords: ['jobber alternative for contractors', 'jobber vs saguaro', 'jobber construction alternative'],
  },
  jobnimbus: {
    slug: 'jobnimbus',
    name: 'JobNimbus',
    tagline: 'CRM and project management for roofing and exterior contractors',
    targetMarket: 'Roofing and exterior contractors',
    startingPrice: '$200/mo',
    annualRequired: false,
    setupTime: '1–2 weeks',
    perSeat: false,
    hasAITakeoff: false,
    hasLienWaivers: false,
    hasCertifiedPayroll: false,
    hasFieldApp: true,
    appStoreRequired: true,
    hasOfflineMode: false,
    hasBidIntelligence: false,
    hasClientPortal: true,
    hasSubPortal: false,
    weaknesses: [
      'Roofing-focused — limited for GCs doing multiple trades',
      'No AI takeoff or automated estimating',
      'No lien waivers or payment compliance tools',
      'No certified payroll for prevailing wage work',
      'No subcontractor management or compliance portal',
    ],
    bestFor: 'Roofing and exterior contractors who need CRM and simple job management',
    saguaroAdvantage: 'Full GC platform: multi-trade, AI takeoff, lien waivers, certified payroll — vs JobNimbus\'s roofing-only scope',
    heroHeadline: 'Beyond Roofing CRM:\nThe Full GC Platform JobNimbus Can\'t Be',
    heroSubheadline: 'JobNimbus is built for roofing. Saguaro is built for any GC: AI takeoff, lien waivers in 50 states, certified payroll, multi-trade bid management, and a full field app.',
    metaTitle: 'Saguaro vs JobNimbus — Full Comparison 2025',
    metaDescription: 'JobNimbus vs Saguaro: JobNimbus is roofing-focused with no AI takeoff, lien waivers, or certified payroll. Saguaro is the full-platform alternative for general contractors.',
    searchKeywords: ['jobnimbus alternative', 'jobnimbus vs saguaro', 'jobnimbus replacement for GC'],
  },
  esub: {
    slug: 'esub',
    name: 'eSUB',
    tagline: 'Project management for specialty subcontractors',
    targetMarket: 'Specialty subcontractors',
    startingPrice: '$89/user/mo',
    annualRequired: true,
    setupTime: '2–4 weeks',
    perSeat: true,
    hasAITakeoff: false,
    hasLienWaivers: true,
    hasCertifiedPayroll: false,
    hasFieldApp: true,
    appStoreRequired: true,
    hasOfflineMode: true,
    hasBidIntelligence: false,
    hasClientPortal: false,
    hasSubPortal: true,
    weaknesses: [
      'Per-seat pricing — costs scale sharply with team size',
      'Subcontractor focus only — not built for GCs',
      'No AI takeoff or automated estimating',
      'No bid intelligence or win-rate analysis',
      'Annual contract required',
    ],
    bestFor: 'Specialty subcontractors who need time tracking and field management',
    saguaroAdvantage: 'GC-first platform with AI takeoff, bid intelligence, and flat pricing vs eSUB\'s per-seat subcontractor focus',
    heroHeadline: 'eSUB Is for Subs.\nSaguaro Is Built for GCs.',
    heroSubheadline: 'eSUB is designed for specialty subs and charges per seat. Saguaro gives GCs AI takeoff, bid intelligence, AIA pay apps, and lien waivers — flat rate, whole team.',
    metaTitle: 'Saguaro vs eSUB — Full Comparison 2025',
    metaDescription: 'eSUB vs Saguaro for general contractors: per-seat vs flat rate, sub-focused vs GC-first, no AI vs AI takeoff. See the full comparison.',
    searchKeywords: ['esub alternative', 'esub vs saguaro', 'esub replacement for general contractor'],
  },
};

export const COMPETITOR_SLUGS = Object.keys(COMPETITORS);
