import { PDFDocument, StandardFonts, rgb, PageSizes } from 'pdf-lib';
import { fmtCurrency, saveDocument } from '../pdf-engine';

/**
 * Branded invoice PDF — the real document behind every invoice row.
 * Modeled on purchase-order-generator: gold letterhead, vendor block,
 * amount/tax/total ladder, due date, terms. Stored via saveDocument()
 * ('documents' private bucket + generated_documents row) so the invoice
 * becomes a numbered artifact with a real .pdf extension, not just a DB row.
 */
export interface InvoicePdfInput {
  invoiceId: string;
  tenantId: string;
}

export async function generateInvoicePdf(input: InvoicePdfInput): Promise<{
  pdfBytes: Uint8Array;
  pdfUrl: string;
  invoiceNumber: string;
}> {
  const { createServerClient } = await import('../supabase-server');
  const db = createServerClient() as any;

  const { data: inv, error } = await db
    .from('invoices')
    .select('*')
    .eq('id', input.invoiceId)
    .eq('tenant_id', input.tenantId)
    .single();
  if (error || !inv) throw new Error('Invoice not found');

  let projectName = '';
  if (inv.project_id) {
    const { data: p } = await db.from('projects').select('name, address, city, state, zip').eq('id', inv.project_id).maybeSingle();
    if (p) projectName = [p.name, [p.address, p.city, p.state, p.zip].filter(Boolean).join(', ')].filter(Boolean).join(' — ');
  }
  const { data: tenant } = await db.from('tenants').select('name').eq('id', input.tenantId).maybeSingle();

  // Money is server-canonical: NUMERIC arrives as text — Number() everything,
  // and a stale 0 total defers to amount + tax.
  const amount = Number(inv.amount) || 0;
  const tax = Number(inv.tax) || 0;
  const total = Number(inv.total) > 0 ? Number(inv.total) : amount + tax;
  const invoiceNumber = inv.invoice_number || `INV-${String(inv.id).slice(0, 6).toUpperCase()}`;

  const pdf = await PDFDocument.create();
  const page = pdf.addPage(PageSizes.Letter);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const { width, height } = page.getSize();
  const M = 46;

  // Gold letterhead
  page.drawRectangle({ x: 0, y: height - 44, width, height: 44, color: rgb(0.831, 0.627, 0.09) });
  page.drawText('INVOICE', { x: M, y: height - 30, size: 16, font: bold, color: rgb(0.05, 0.07, 0.09) });
  page.drawText((tenant?.name || 'SAGUARO CONTROL SYSTEMS').toUpperCase(), {
    x: M, y: height - 40, size: 7, font, color: rgb(0.2, 0.1, 0),
  });
  page.drawText(`# ${invoiceNumber}`, { x: width - 170, y: height - 30, size: 12, font: bold, color: rgb(0.05, 0.07, 0.09) });

  let y = height - 78;
  const line = (label: string, value: string, opts?: { big?: boolean; goldBar?: boolean }) => {
    if (!value) return;
    if (opts?.goldBar) {
      page.drawRectangle({ x: M - 8, y: y - 6, width: width - 2 * (M - 8), height: 22, color: rgb(0.98, 0.94, 0.85) });
    }
    page.drawText(label.toUpperCase(), { x: M, y, size: 7.5, font: bold, color: rgb(0.45, 0.45, 0.45) });
    page.drawText(value, {
      x: M + 150, y: y - (opts?.big ? 2 : 0),
      size: opts?.big ? 13 : 10, font: opts?.big ? bold : font, color: rgb(0.08, 0.08, 0.08),
    });
    y -= opts?.big ? 26 : 20;
  };

  const dateStr = (v?: string | null) => {
    if (!v) return '';
    const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(String(v));
    if (!m) return String(v);
    return new Date(Number(m[1]), Number(m[2]) - 1, Number(m[3])).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
  };

  line('Billed To', inv.vendor_name || '');
  if (inv.vendor_email) line('Email', inv.vendor_email);
  if (projectName) line('Project', projectName);
  if (inv.description) line('Description', String(inv.description).slice(0, 110));
  if (inv.cost_code) line('Cost Code', String(inv.cost_code));
  line('Invoice Date', dateStr(inv.created_at));
  line('Due Date', dateStr(inv.due_date));
  y -= 8;

  // Totals ladder
  page.drawLine({ start: { x: M, y: y + 8 }, end: { x: width - M, y: y + 8 }, thickness: 0.75, color: rgb(0.8, 0.8, 0.8) });
  line('Amount', fmtCurrency(amount));
  if (tax > 0) line('Tax', fmtCurrency(tax));
  line('Total Due', fmtCurrency(total), { big: true, goldBar: true });

  y -= 10;
  line('Terms', inv.notes ? String(inv.notes).slice(0, 160) : 'Payment due by the date above.');

  page.drawText('Generated by Saguaro Control Systems — saguarocontrol.net', {
    x: M, y: 30, size: 7, font, color: rgb(0.55, 0.55, 0.55),
  });

  const pdfBytes = await pdf.save();
  const pdfUrl = await saveDocument(
    inv.project_id || input.tenantId,
    'invoice',
    pdfBytes,
    { invoiceId: inv.id, invoiceNumber, total, vendor: inv.vendor_name },
    input.tenantId,
  );
  return { pdfBytes, pdfUrl, invoiceNumber };
}
