export const meta = {
  name: 'wave4-ui',
  description: 'Final UI + nav: pay-app/CO/talk edit-delete, milestones, lien/insurance screens, complete More directory + alert destinations',
  phases: [{ title: 'Build' }],
}
const SCHEMA = { type: 'object', additionalProperties: false, properties: { screen: { type: 'string' }, built: { type: 'array', items: { type: 'string' } }, compiles: { type: 'boolean' }, notes: { type: 'string' } }, required: ['screen', 'built', 'compiles'] }
const R = 'D:/saguaro-mobile/'
const COMMON = `React Native (Expo, expo-router) app. The API client ${R}src/lib/api.ts ALREADY has every method (read it to confirm): payApps.update/remove, changeOrders.update/remove, safety.updateTalk/removeTalk, schedule.createMilestone/updateMilestone/removeMilestone, lienWaivers.list/sign, insurance.list, plus all the create/update/delete from earlier. DO NOT edit api.ts.
Use the existing patterns in the codebase (react-native-modal bottom sheets, theme tokens C, PressScale, AppIcon, Toast, sectioned form cards, chip selectors, gold CTAs, tinted icon chips at color@~12% with the icon in full color, 0.5px C.b1 hairlines, sentence-case headers, SafeAreaView). Success -> haptic + Toast + reload the screen's data; Alert-confirm before delete. Run npx tsc --noEmit in ${R}; report compiles. Don't break existing flows.`

const SCREENS = {
  'financials': { file: 'app/project/[id]/financials.tsx', build: `In the existing pay-app detail sheet add EDIT (prefill the create-pay-app form -> api.payApps.update(id, body)) and DELETE (Alert confirm -> api.payApps.remove(id) -> reload). In the change-order detail sheet add EDIT (prefill create-CO form -> api.changeOrders.update(id, body)) and DELETE (api.changeOrders.remove(id)). Keep the existing detail fields + status workflow (submit/certify/approve/paid, approve/reject).` },
  'safety-schedule': { file: 'app/project/[id]/safety.tsx', also: 'app/project/[id]/schedule.tsx', build: `safety.tsx: the toolbox-talk row already opens a detail modal — add EDIT (prefill the talk create form: topic/presenter/talk_date/content/attendee_count -> api.safety.updateTalk(id, body)) and DELETE (Alert -> api.safety.removeTalk(id) -> reload). schedule.tsx: add MILESTONE management — a '+ Milestone' action that creates one (api.schedule.createMilestone({project_id, title, milestone_date})), and make each rendered milestone diamond tappable to a small edit/delete sheet (api.schedule.updateMilestone(id,body) / api.schedule.removeMilestone(id)). Keep the existing task create/edit/delete.` },
  'compliance-screens': { file: 'app/lien-waivers.tsx', also: 'app/insurance.tsx', build: `CREATE two NEW stack screens (expo-router file routes). (1) ${R}app/lien-waivers.tsx -> route '/lien-waivers': a SafeAreaView screen with a back button + 'Lien waivers' title that loads api.lienWaivers.list() and renders the waivers (claimant_name, waiver_type, amount, status pill) as cards; tapping one opens a detail sheet with a 'Mark signed' action (api.lienWaivers.sign(id,{signedBy})) when not signed; pull-to-refresh; loading/empty/error states. (2) ${R}app/insurance.tsx -> route '/insurance': same shell, title 'Insurance / COIs', loads api.insurance.list() and renders certificates (sub_name/carrier/policy_type/expiry_date/coverage_amount/status) read-only with an expiring-soon highlight. Match the app's card/chip/hairline style. Use the existing useAuth/api imports as other screens do.` },
  'nav': { file: 'app/(tabs)/index.tsx', also: 'app/(tabs)/more.tsx', build: `FINISH THE NAV. index.tsx (home 'Needs attention'): wire the two dead alerts — 'COIs Expiring' onPress -> router.push('/insurance'); 'Pending Lien Waivers' onPress -> router.push('/lien-waivers'); show the chevron on these now that they navigate. more.tsx: reorganize into a COMPLETE grouped directory (like a proper 'More' index): keep Equipment + the live data sections, and add a 'Compliance' group with rows 'Lien waivers' -> router.push('/lien-waivers') and 'Insurance / COIs' -> router.push('/insurance') (tinted icon chips, chevrons). Keep the existing 'More tools' on-web rows and Sign out. Ensure every row either navigates to a real screen or is clearly marked 'On web'. Keep it the restrained enterprise style.` },
}

log(`Wave 4 UI + nav across ${Object.keys(SCREENS).length} units`)
const results = await parallel(Object.entries(SCREENS).map(([k, s]) =>
  () => agent(`${COMMON}\n\n=== UNIT: ${k} ===\nPrimary file: ${R}${s.file}${s.also ? '\nAlso edit/create: ' + R + s.also : ''}\nBUILD:\n${s.build}`, { label: k, phase: 'Build', schema: SCHEMA })))
return { screens: results.filter(Boolean) }
