import { NextRequest, NextResponse } from 'next/server';
import { createServerClient, getUser } from '@/lib/supabase-server';
import {
  PDFDocument,
  StandardFonts,
  rgb,
  PageSizes,
} from 'pdf-lib';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * POST /api/projects/[projectId]/rfis/export   body { rfi_ids: string[] }
 * GET  /api/projects/[projectId]/rfis/export?ids=a,b,c   (or all open RFIs)
 *
 * Produces a printable PDF of the project's RFIs and returns it as a binary
 * file response (application/pdf). Mirrors the pdf-lib approach used by
 * lib/pdf-engine.ts and app/api/reports/export/route.ts.
 *
 * Caller: app/field/rfis/page.tsx → handleBulkExport()
 *   POST { rfi_ids } → reads res.blob() → downloads `rfis-export-*.pdf`
 */

type Row = Record<string, unknown>;

// ─── Brand colors (match pdf-engine) ─────────────────────────────────────────
const GOLD = rgb(0.831, 0.627, 0.09);
const DARK = rgb(0.051, 0.067, 0.086);
const GRAY = rgb(0.4, 0.4, 0.4);
const LGRAY = rgb(0.94, 0.94, 0.94);
const WHITE = rgb(1, 1, 1);
const BLACK = rgb(0, 0, 0);

function fmtDate(d?: unknown): string {
  if (!d) return '';
  const dt = new Date(String(d));
  if (isNaN(dt.getTime())) return String(d);
  return dt.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

function draw(page: any, text: string, x: number, y: number, size: number, font: any, color = BLACK) {
  page.drawText(String(text ?? '').slice(0, 200), { x, y, size, font, color });
}

/** Word-wrap a paragraph, returning the new y after drawing. */
function wrap(page: any, text: string, x: number, startY: number, font: any, size: number, maxChars: number, color = DARK): number {
  let y = startY;
  const words = String(text ?? '').replace(/\s+/g, ' ').trim().split(' ');
  let line = '';
  for (const w of words) {
    if ((line + ' ' + w).trim().length > maxChars) {
      draw(page, line.trim(), x, y, size, font, color);
      y -= size + 3;
      line = w;
    } else {
      line = (line + ' ' + w).trim();
    }
  }
  if (line.trim()) {
    draw(page, line.trim(), x, y, size, font, color);
    y -= size + 3;
  }
  return y;
}

async function buildRfiPdf(rfis: Row[], projectName: string): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const reg = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const MARGIN = 40;
  const today = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

  // Empty-state page so we always return a valid PDF.
  const list = rfis.length > 0 ? rfis : [];

  let page = doc.addPage(PageSizes.Letter);
  let { width, height } = page.getSize();

  function header(p: any) {
    const { width: w, height: h } = p.getSize();
    p.drawRectangle({ x: 0, y: h - 56, width: w, height: 56, color: DARK });
    draw(p, 'SAGUARO', MARGIN, h - 24, 13, bold, GOLD);
    draw(p, 'REQUEST FOR INFORMATION — LOG', MARGIN + 90, h - 24, 12, bold, WHITE);
    draw(p, projectName || 'Project', MARGIN, h - 42, 9, reg, rgb(0.7, 0.7, 0.7));
    draw(p, `Generated ${today}  •  ${list.length} RFI(s)`, w - 230, h - 42, 8, reg, rgb(0.7, 0.7, 0.7));
  }

  function footer(p: any, n: number) {
    const { width: w } = p.getSize();
    p.drawLine({ start: { x: MARGIN, y: 36 }, end: { x: w - MARGIN, y: 36 }, color: LGRAY, thickness: 0.5 });
    draw(p, `Generated by Saguaro Control Systems — ${today}`, MARGIN, 22, 7, reg, GRAY);
    draw(p, `Page ${n}`, w - MARGIN - 40, 22, 7, reg, GRAY);
  }

  header(page);
  let y = height - 80;
  let pageNum = 1;

  function ensureSpace(needed: number) {
    if (y - needed < 56) {
      footer(page, pageNum);
      page = doc.addPage(PageSizes.Letter);
      ({ width, height } = page.getSize());
      header(page);
      y = height - 80;
      pageNum++;
    }
  }

  if (list.length === 0) {
    draw(page, 'No RFIs selected for export.', MARGIN, y, 11, reg, GRAY);
    footer(page, pageNum);
    return await doc.save();
  }

  const today10 = new Date().toISOString().split('T')[0];

  for (const r of list) {
    ensureSpace(120);

    const num = (r.rfi_number as string) || '';
    const status = String(r.status || 'open');
    const isOverdue = status === 'open' && !!r.due_date && String(r.due_date) < today10;

    // Card header bar
    page.drawRectangle({ x: MARGIN, y: y - 20, width: width - MARGIN * 2, height: 20, color: LGRAY });
    draw(page, `${num}${num ? '  •  ' : ''}${String(r.subject || 'Untitled RFI')}`, MARGIN + 6, y - 14, 10, bold, DARK);

    // Status pill (right aligned)
    const pillText = isOverdue ? 'OVERDUE' : status.toUpperCase();
    const pillColor = isOverdue ? rgb(0.8, 0.2, 0.1) : status === 'answered' || status === 'closed' ? rgb(0.1, 0.5, 0.2) : GOLD;
    draw(page, pillText, width - MARGIN - 70, y - 14, 8, bold, pillColor);
    y -= 28;

    // Meta line
    const meta: string[] = [];
    if (r.spec_section) meta.push(`Spec: ${r.spec_section}`);
    if (r.drawing_reference) meta.push(`Dwg: ${r.drawing_reference}`);
    if (r.due_date) meta.push(`Due: ${fmtDate(r.due_date)}`);
    if (r.submitted_by) meta.push(`By: ${r.submitted_by}`);
    if (r.priority) meta.push(`Priority: ${r.priority}`);
    if (meta.length) {
      draw(page, meta.join('   |   '), MARGIN + 6, y, 8, reg, GRAY);
      y -= 16;
    }

    // Question
    if (r.question) {
      draw(page, 'QUESTION', MARGIN + 6, y, 8, bold, DARK);
      y -= 13;
      y = wrap(page, String(r.question), MARGIN + 6, y, reg, 9, 95);
      y -= 4;
    }

    // Answer
    if (r.answer) {
      ensureSpace(40);
      draw(page, 'ANSWER', MARGIN + 6, y, 8, bold, rgb(0.1, 0.45, 0.2));
      y -= 13;
      y = wrap(page, String(r.answer), MARGIN + 6, y, reg, 9, 95);
      if (r.answered_by) {
        draw(page, `— ${r.answered_by}${r.answered_date ? ', ' + fmtDate(r.answered_date) : ''}`, MARGIN + 6, y, 7, reg, GRAY);
        y -= 12;
      }
    }

    // Divider
    page.drawLine({ start: { x: MARGIN, y: y - 4 }, end: { x: width - MARGIN, y: y - 4 }, color: LGRAY, thickness: 0.5 });
    y -= 18;
  }

  footer(page, pageNum);
  return await doc.save();
}

async function loadRfis(projectId: string, tenantId: string, ids: string[]) {
  const db = createServerClient();
  let q = db.from('rfis').select('*').eq('tenant_id', tenantId).eq('project_id', projectId);
  if (ids.length > 0) q = q.in('id', ids);
  const { data } = await q.order('rfi_number', { ascending: true });
  return (data as Row[]) || [];
}

async function projectName(projectId: string, tenantId: string): Promise<string> {
  try {
    const db = createServerClient();
    const { data } = await db
      .from('projects')
      .select('name')
      .eq('id', projectId)
      .eq('tenant_id', tenantId)
      .single();
    return ((data as Row | null)?.name as string) || '';
  } catch {
    return '';
  }
}

async function respond(rfis: Row[], pname: string): Promise<NextResponse> {
  const bytes = await buildRfiPdf(rfis, pname);
  return new NextResponse(Buffer.from(bytes), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="rfis-export-${Date.now()}.pdf"`,
      'Cache-Control': 'no-store',
    },
  });
}

export async function POST(req: NextRequest, { params }: { params: Promise<{ projectId: string }> }) {
  const { projectId } = await params;

  const user = await getUser(req);
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  try {
    let body: Row = {};
    try { body = await req.json(); } catch { /* empty body — export all */ }

    const ids = Array.isArray(body.rfi_ids)
      ? (body.rfi_ids as unknown[]).map((x) => String(x))
      : Array.isArray(body.ids)
        ? (body.ids as unknown[]).map((x) => String(x))
        : [];

    const [rfis, pname] = await Promise.all([
      loadRfis(projectId, user.tenantId, ids),
      projectName(projectId, user.tenantId),
    ]);

    return await respond(rfis, pname);
  } catch {
    return NextResponse.json({ error: 'RFI export failed' }, { status: 500 });
  }
}

export async function GET(req: NextRequest, { params }: { params: Promise<{ projectId: string }> }) {
  const { projectId } = await params;

  const user = await getUser(req);
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  try {
    const idsParam = req.nextUrl.searchParams.get('ids') || '';
    const ids = idsParam.split(',').map((s) => s.trim()).filter(Boolean);

    const [rfis, pname] = await Promise.all([
      loadRfis(projectId, user.tenantId, ids),
      projectName(projectId, user.tenantId),
    ]);

    return await respond(rfis, pname);
  } catch {
    return NextResponse.json({ error: 'RFI export failed' }, { status: 500 });
  }
}
